#!/bin/bash
# atget - download trailers from Apple website

# Usage if no parameters given
if [ -z $@ ]; then
  echo " atget <apple-trailer-url>"; exit
fi

# Prepend 'h' before resolution to create a valid url
newurl=$(echo $@ | sed 's/_\([0-9]*[0-9][0-9][0-9]\)p.mov/_h\1p.mov/g')

# Download trailer and save to the desktop
wget -U QuickTime/7.6.2 "$newurl" #-O $HOME/Videos/${@##*/}

# Play trailer with mplayer (using 200MB cache to be sure trailer is dl'd first)
#mplayer -cache 200000 -user-agent 'QuickTime/7.6.2 (qtver=7.6.2;os=Windows NT 5.1Service Pack 3)' $newurl
