#!/bin/sh
# conkywonky
# ----------
# Many moons ago, Conky did not automatically restart when changes were
# made to its config files. This script was used to restart it. It does not
# really serve any purpose now, but I like the name and some people may still
# be using/referencing it.

killall conky
killall conkympd.sh
conky -q
conky -q -c /home/n2burns/.conky_short
conky -q -c /home/n2burns/.conky_mpd
/home/n2burns/./conkympd.sh
exit
