#!/bin/sh
# conkywonky
# ----------
# Many moons ago, Conky did not automatically restart when changes were
# made to its config files. This script was used to restart it. It does not
# really serve any purpose now, but I like the name and some people may still
# be using/referencing it.

if [ "$(pidof conky)" ]; then
  killall conky
fi

if [ "$(pidof -x conkympd.sh)" ]; then
  killall conkympd.sh
fi

conky -q
conky -q -c /home/n2burns/code/conky/.conky_short
conky -q -c /home/n2burns/code/conky/.conky_mpd
/home/n2burns/code/conky/./conkympd.sh &
exit
